config/routes.rb
Rails.application.routes.draw do

  resources :restaurants do
    resources :reviews
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

CATEGORIES = ["Chinese", "Italian", "Japanese", "French", "Belgian"]

  validates :name, presence: true
  validates :address, presence: true
  validates :category,
            inclusion: { in: ["Chinese", "Italian", "Japanese", "French", "Belgian"] },
presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :restaurant_id, presence: true
  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }, numericality: true, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone_number, :category)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

 before_action :set_restaurant

 def new
   @review = Review.new
 end

 def create
   @review = @restaurant.reviews.create(reviews_params)
   if @review.save
   redirect_to restaurant_path(@restaurant)
 else
     render :new
   end
 end
 def destroy
   @review = Review.find(params[:id])
   @review.destroy
   redirect_to restaurant_path(@restaurant)
 end

 private

 def set_restaurant
   @restaurant = Restaurant.find(params[:restaurant_id])
 end

 def reviews_params
   params.require(:review).permit(:content, :rating)
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Add these line for detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="container">
 <div class="row">
   <div class="col-xs-12 col-md-6 col-md-offset-3">

     <%= simple_form_for(@restaurant) do |f| %>
 <%= f.error_notification %>

 <div class="form-inputs">
   <%= f.input :name %>
   <%= f.input :address %>
   <%= f.input :phone_number %>
   <%= f.input :category, as: :select, collection: Restaurant::CATEGORIES %>


 </div>

 <div class="form-actions">
   <%= f.button :submit %>
 </div>
<% end %>

   </div>
 </div>
</div>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<div class="container">
 <div class="row">
   <div class="col-xs-12 col-md-8 col-md-offset-2">
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>


<table class="table table-hover">
 <thead>
   <tr>
     <th>Name</th>
     <th>Address</th>
     <th>Phone number</th>
     <th>Category</th>
     <th colspan="3"></th>
   </tr>
 </thead>

 <tbody>
   <% @restaurants.each do |restaurant| %>
     <tr>
       <td><%= restaurant.name %></td>
       <td><%= restaurant.address %></td>
       <td><%= restaurant.phone_number %></td>
       <td><%= restaurant.category %></td>
       <td><%= link_to 'Show', restaurant %></td>
       <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
       <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
     </tr>
   <% end %>
 </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path, class: "btn btn-primary" %>
</div>
</div>
</div>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<div class="header padded text-center">
  <h1><%= @restaurant.name %></h1>

  <div id="address">
    <h4>Address: </h4>
    <%= @restaurant.address %>
  </div>
  <% if @restaurant.phone_number %>
    <div id="phone-number">
      <h4>Contact details: </h4>
      <%= @restaurant.phone_number %>
    </div>
  <% end %>

</div>
<% if @restaurant.reviews.first %>
 <div class="wrapper-grey padded text-center">
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-md-offset-2 ">
          <h4>Rating</h4>
        </div>

          <h4>Content</h4>
        </div>

      </div>

      <% @restaurant.reviews.each do |review| %>
      <div class="wrapper-grey padded text-center">
      <div class="container">

        <div class="row">
          <div class="col-md-4 col-md-offset-2 ">
          <%= raw ("#{icon('star-o')} " * review.rating.to_i)  %>
        </div>

          <%= review.content %>

          <%= link_to 'Delete', restaurant_review_path(restaurant_id: @restaurant.id, id: review.id), method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
    </div>
          <% end %>
    <hr>
  </div>
<% end %>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %> |
<%= link_to 'Add Review', new_restaurant_review_path(@restaurant) %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<div class="container">
 <div class="row">
   <h1 class="text-center">Add a Review</h1>

   <div class="col-xs-12 col-md-offset-3 col-md-6">

     <%= simple_form_for [@restaurant, @review] do |f| %>
      <% if @restaurant.errors.any? %>
   <div id="error_explanation">
     <ul>
     <% @restaurant.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
     </ul>
   </div>
 <% end %>

       <%= f.input :content %>
         <%= f.input :rating %>
       <%= f.submit class: "btn btn-primary" %>
     <% end %>
   </div>
 </div>
</div>